apiVersion: v1

kind: Pod

metadata: 
  name: multicontainerpod
  namespace: multicontainerns

spec:
  containers:
  - name: container1
    image: nginx:latest

    ports:
    - containerPort: 80

  - name: container2
    image: linuxserver/firefox

    ports:
    - containerPort: 3000